title: Josh Hawthorne
mail: josh@joshhawthorne.com
description: aka Thorn Hawchorn
baseurl: ""
url: ""
twitter_username: joshhawthorne
github_username:  joshhawthorne
facebook_username:  joshhawthorne

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

